version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bolsas
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: gunicorn -k eventlet -w 1 automacao_cotacoes:app -b 0.0.0.0:5000
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bolsas
      - SECRET_KEY=troque_esta_chave
    depends_on:
      - db
volumes:
  pgdata:
